spring:
  application:
    name: my-service  # 服务名称，用于在 Eureka Server 中标识该服务

server:
  port: 8080  # 服务端口

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server 的地址
    registerWithEureka: true  # 是否将自己注册到 Eureka Server
    fetchRegistry: true       # 是否从 Eureka Server 获取注册表信息
  instance:
    preferIpAddress: true  # 使用 IP 地址注册，而不是主机名
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}  # 实例 ID
